apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-checker
  namespace: default
spec:
  replicas: 1  # Run one instance of the health checker
  selector:
    matchLabels:
      app: health-checker
  template:
    metadata:
      labels:
        app: health-checker
    spec:
      containers:
      - name: health-checker
        image: simransar/health-checker:latest
        command: ["python", "health_checker.py"]
        resources:                             # Define resource requests and limits
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

